### ISSUE TITLE
Analyse profiling tools for C

### ISSUE THREAD

**Issue by ashish-17** [ashish-17/WaitFreeMemAlloc#1]
List down all the available profiling tools for C
Short-list the tools based on compiler compatibility and supported features.

**Comment by architaagarwal** [comment]
Instruments - comes with Xcode - GUI - has a lot of features like detecting memory leaks, time profiling etc, can show per core as well as per thread time information as well.

GProf - comes with gcc - not supported on mac

Shark - used to some with Xcode - discontinued now

DTrace - this is the underlying support of Instruments. Instruments is its GUI.

OpenPAT - can be used to measure hotspots, control flow, data flow and other information. A pdf said (http://www.openpat.org/docs/OpenPAT%20--%20Introduction.pdf) that it is more efficient than Valgrind but i think the pdf is from its inventors. Can't find much on how much is it used.

gperftools - Can check efficiency of multithreaded applications. It works on MacOS 10.9

Valgrind - it's not a profiler but a memory management tool which can very effectively detect memory leaks. It also comes with two tools - cachegrind and callgrind. Both help in analysing time (http://c.learncodethehardway.org/book/ex41.html).
KCachegrind built on top of it is a GUI which interprets the outputs from both. For mac i think we have qcachegrind instead of kcachegrind.

RotateRightZoom  - supports most compiled languages on ARM and x86 processors. Don't know it it would work on mine. Has a GUI as well. (http://www.rotateright.com/zoom-quick-start/zoom-quick-start.html)

**Comment by ashish-17** [comment]
Did u check following profilers?
- Poor man's profiler
- oprofile
- TAU - tuning and performance utilities
- Code analyst by AMD

**Comment by architaagarwal** [comment]
Poor man's profiler (PMP) - didn't get much whether MAC is supported or not.

Oprofile - It's wiki page says that call graphs are supported by only ARM and x_86 processors.  Seems to work on OSX. But it seems obsolete now. (http://stackoverflow.com/questions/7024467/is-oprofile-still-alive-and-well/7024840#7024840)

CodeAnalyst - specifically designed for AMD processors but can be used for other processors as well. It is based on oprofile. Uses oprofile as its backend. Works for both x86 and x86_64 machines. Don't know if it works for Mac

**Comment by ashish-17** [comment]
- Instruments
  - http://stackoverflow.com/questions/11445619/profiling-c-on-mac-os-x
  - http://www.raywenderlich.com/23037/how-to-use-instruments-in-xcode
- gperftools 
  - https://code.google.com/p/gperftools/wiki/GooglePerformanceTools
  - http://stackoverflow.com/questions/13619974/how-exactly-does-gperftools-cpu-profiler-start
- Valgrind
  - http://c.learncodethehardway.org/book/ex41.html
- KCachegrind
   -
- Zoom
  - http://www.rotateright.com/zoom-quick-start/zoom-quick-start.html
  - https://www.youtube.com/watch?v=MtNiruL7ah4
- Oprofile
  - https://www.novell.com/coolsolutions/feature/11789.html
  - http://people.redhat.com/wcohen/Oprofile.pdf

**Comment by ashish-17** [comment]
Test code for analysing output of performance tools.
1. Write a simple hello world C program.
2. Write a c program that calls malloc 10000 times each time asking random memory. Don't free this memory.
3. Write another C program that call above routine in 10 different threads.
4. Write some C program that allocates and then deallocates some memory. 
5. Write a C program that calls this routine in 10 different threads.

**Comment by architaagarwal** [comment]
Callgrind
 - https://kcachegrind.github.io/html/Documentation.html
 - Doesn't show annotated code line-by-line (probably a mac bug)
 - Don't know if time that it is showing is one time time or across all the call in LHS panel.
 - Also, what is cycle 2. Is it in some way indicative of the threads. I don't think so.

**Comment by architaagarwal** [comment]
Callgrind continued
 - Also the call graphs of the child node and parent node always seemed to have same percentage.
 - GUI seems different from the link given up. That one is KDE based. Should we change.
